blank_issues_enabled: false
contact_links:
  - name: Builder DAO Community Support
    url: https://discord.gg/r4vNRUTXY9
    about: Reach out to our team on Discord for support.
  - name: About Builder DAO
    url: https://builderdao.notion.site/
    about: Learn more about Builder DAO.
